Hos
CosmoStat/cosmostat pull request #18
Opened 2023-11-08 09:34 UTC by jstarck

Creation of a class for multi-scale peaks count and wavelet-l1 norm statistics, taking into account the mask. 
Fix the bug on mass mapping for non square images.
Write two test routines to show to use the class 
   - test_hos_cfis()
   - test_hos_test1()

2023-11-14 16:11 UTC, AndreasTersenov commented
There are a couple of small issues:

1. In `hos_peaks_l1.py` there is a semicolon (;) at the beginning of line 659 that should be removed (possibly this is what causes the check fail).
2. There are some instances in the repo where `np.float`  is used (I found some in `starlet.py` but there may be some in other places as well). This is deprecated since NumPy 1.20 so those instances should be replaced with either just `float` or `np.float64`. Doing this will not modify any behavior and is safe.
3.  In the test routine functions, in `hos_peaks_l1.py`, some directories paths are defined, but they use your local paths. If we want these test routines to be able to be ran by anyone who installs the package, this should be changed.

2024-04-05 12:16 UTC, sfarrens requested changes

2024-04-05 12:16 UTC, sfarrens commented on pycs/misc/stats.py
> +def mad(input_data, axis=None, keepdims=False):
The MAD is already implemented in ModOpt

2024-04-05 12:16 UTC, sfarrens commented on pycs/astro/wl/mass_mapping.py
> +# =============================================================================
Why is the commented out. Code should either be in or out not half way between.

2024-04-05 12:16 UTC, sfarrens commented on pycs/astro/wl/mass_mapping.py
> +        # =============================================================================
Who is this for?

2024-04-05 12:16 UTC, sfarrens commented on pycs/astro/wl/hos_peaks_l1.py
> +#     plt.show()
In or out?

2024-04-05 12:16 UTC, sfarrens commented on pycs/astro/wl/hos_peaks_l1.py
> +# test_hos_test1()
Remove

2024-04-23 19:14 UTC, merged